// Mock data used until the matching Supabase tables exist.
// Shapes mirror the planned tables so pages won't change when real data lands.

export const events = [
  {
    id: "evt-001",
    title: "Rise in dengue cases",
    type: "Disease outbreak",
    region: "Western Province",
    severity: "high",
    status: "active",
    startedAt: "2026-09-22",
    articleCount: 4,
  },
  {
    id: "evt-002",
    title: "Inter-monsoon flooding",
    type: "Natural disaster",
    region: "Ratnapura & Kalutara",
    severity: "high",
    status: "active",
    startedAt: "2026-09-30",
    articleCount: 3,
  },
  {
    id: "evt-003",
    title: "Leptospirosis cases after floods",
    type: "Disease outbreak",
    region: "Sabaragamuwa Province",
    severity: "medium",
    status: "monitoring",
    startedAt: "2026-10-02",
    articleCount: 2,
  },
  {
    id: "evt-004",
    title: "Seasonal influenza",
    type: "Seasonal",
    region: "Island-wide",
    severity: "medium",
    status: "monitoring",
    startedAt: "2026-09-10",
    articleCount: 2,
  },
  {
    id: "evt-005",
    title: "Import clearance delays",
    type: "Supply disruption",
    region: "Colombo Port",
    severity: "medium",
    status: "active",
    startedAt: "2026-09-28",
    articleCount: 1,
  },
  {
    id: "evt-006",
    title: "Global API price increase",
    type: "Supply disruption",
    region: "International",
    severity: "low",
    status: "monitoring",
    startedAt: "2026-09-05",
    articleCount: 1,
  },
  {
    id: "evt-007",
    title: "Dry spell in the Northern Province",
    type: "Natural disaster",
    region: "Jaffna",
    severity: "low",
    status: "resolved",
    startedAt: "2026-08-15",
    articleCount: 1,
  },
];

export const articles = [
  {
    id: "art-001",
    title: "Dengue cases climb in Colombo and Gampaha districts",
    source: "Health Ministry Bulletin",
    sourceType: "Government",
    eventId: "evt-001",
    publishedAt: "2026-10-03",
    relevance: "high",
  },
  {
    id: "art-002",
    title: "Flood warnings issued for Ratnapura and Kalutara",
    source: "Disaster Management Update",
    sourceType: "Government",
    eventId: "evt-002",
    publishedAt: "2026-10-01",
    relevance: "high",
  },
  {
    id: "art-003",
    title: "Hospitals prepare for post-flood leptospirosis cases",
    source: "Regional News",
    sourceType: "News",
    eventId: "evt-003",
    publishedAt: "2026-10-02",
    relevance: "medium",
  },
  {
    id: "art-004",
    title: "Influenza activity increasing across South Asia",
    source: "International Health Report",
    sourceType: "International",
    eventId: "evt-004",
    publishedAt: "2026-09-25",
    relevance: "medium",
  },
  {
    id: "art-005",
    title: "Container backlog slows pharmaceutical imports",
    source: "Shipping & Trade News",
    sourceType: "News",
    eventId: "evt-005",
    publishedAt: "2026-09-29",
    relevance: "medium",
  },
  {
    id: "art-006",
    title: "Active ingredient prices rise on global markets",
    source: "Pharma Industry Digest",
    sourceType: "International",
    eventId: "evt-006",
    publishedAt: "2026-09-07",
    relevance: "low",
  },
  {
    id: "art-007",
    title: "Fever clinics report higher attendance in Western Province",
    source: "Regional News",
    sourceType: "News",
    eventId: "evt-001",
    publishedAt: "2026-09-27",
    relevance: "high",
  },
];

export const medicineImpacts = [
  {
    id: "imp-001",
    medicine: "Paracetamol 500 mg",
    category: "Analgesic",
    eventId: "evt-001",
    direction: "increase",
    expectedChangePct: 35,
    impactLevel: "high",
  },
  {
    id: "imp-002",
    medicine: "Oral Rehydration Salts",
    category: "Electrolyte",
    eventId: "evt-002",
    direction: "increase",
    expectedChangePct: 40,
    impactLevel: "high",
  },
  {
    id: "imp-003",
    medicine: "Normal Saline 0.9% IV",
    category: "IV fluid",
    eventId: "evt-001",
    direction: "increase",
    expectedChangePct: 25,
    impactLevel: "high",
  },
  {
    id: "imp-004",
    medicine: "Doxycycline 100 mg",
    category: "Antibiotic",
    eventId: "evt-003",
    direction: "increase",
    expectedChangePct: 30,
    impactLevel: "medium",
  },
  {
    id: "imp-005",
    medicine: "Oseltamivir 75 mg",
    category: "Antiviral",
    eventId: "evt-004",
    direction: "increase",
    expectedChangePct: 20,
    impactLevel: "medium",
  },
  {
    id: "imp-006",
    medicine: "Insulin (human, 10 ml)",
    category: "Antidiabetic",
    eventId: "evt-005",
    direction: "decrease",
    expectedChangePct: -15,
    impactLevel: "medium",
  },
  {
    id: "imp-007",
    medicine: "Amoxicillin 500 mg",
    category: "Antibiotic",
    eventId: "evt-006",
    direction: "decrease",
    expectedChangePct: -5,
    impactLevel: "low",
  },
];

// Units dispensed: usual monthly average vs the last 30 days.
export const demand = [
  { id: "dem-001", medicine: "Paracetamol 500 mg", unit: "tablets", baseline: 120000, last30Days: 158000 },
  { id: "dem-002", medicine: "Oral Rehydration Salts", unit: "sachets", baseline: 18000, last30Days: 24500 },
  { id: "dem-003", medicine: "Normal Saline 0.9% IV", unit: "bottles", baseline: 9500, last30Days: 11600 },
  { id: "dem-004", medicine: "Doxycycline 100 mg", unit: "capsules", baseline: 14000, last30Days: 16200 },
  { id: "dem-005", medicine: "Oseltamivir 75 mg", unit: "capsules", baseline: 3200, last30Days: 3600 },
  { id: "dem-006", medicine: "Salbutamol inhaler", unit: "inhalers", baseline: 5400, last30Days: 5500 },
  { id: "dem-007", medicine: "Insulin (human, 10 ml)", unit: "vials", baseline: 7800, last30Days: 7100 },
  { id: "dem-008", medicine: "Amoxicillin 500 mg", unit: "capsules", baseline: 42000, last30Days: 41300 },
];

// Placeholder projections for the next four weeks (no model yet).
export const forecasts = [
  { id: "fc-001", medicine: "Paracetamol 500 mg", unit: "tablets", weeklyBaseline: 28000, weeks: [36000, 38500, 37000, 33000] },
  { id: "fc-002", medicine: "Oral Rehydration Salts", unit: "sachets", weeklyBaseline: 4200, weeks: [5800, 6200, 5600, 4900] },
  { id: "fc-003", medicine: "Normal Saline 0.9% IV", unit: "bottles", weeklyBaseline: 2200, weeks: [2700, 2800, 2600, 2400] },
  { id: "fc-004", medicine: "Doxycycline 100 mg", unit: "capsules", weeklyBaseline: 3300, weeks: [4100, 4300, 3900, 3500] },
  { id: "fc-005", medicine: "Oseltamivir 75 mg", unit: "capsules", weeklyBaseline: 750, weeks: [850, 900, 880, 800] },
  { id: "fc-006", medicine: "Insulin (human, 10 ml)", unit: "vials", weeklyBaseline: 1800, weeks: [1650, 1600, 1700, 1800] },
];
